# GrandEntrance v1.1.0
debug: false

trigger:
  mode: OP_OR_PERMISSION   # OP_ONLY | PERMISSION_ONLY | OP_OR_PERMISSION
  permission: "grandentrance.trigger"

exclude_joiner: false
join_cooldown_ticks: 20

title:
  enabled: true
  main: "&eBehold! &6The &lServer Overlord &r&6has arrived!"
  sub: "&7Prepare yourselves, mortals."
  fade_in: 10
  stay: 60
  fade_out: 20

bossbar:
  enabled: true
  text: "&6👑 The Overlord Walks Among You"
  color: PURPLE           # PURPLE, PINK, BLUE, GREEN, RED, YELLOW, WHITE
  style: NOTCHED_20       # PROGRESS | NOTCHED_6 | NOTCHED_10 | NOTCHED_12 | NOTCHED_20
  seconds: 4

sounds:
  enabled: true
  list:
    - { name: ITEM_GOAT_HORN_SOUND_0, volume: 10.0, pitch: 1.0 }
    - { name: ITEM_GOAT_HORN_SOUND_1, volume: 10.0, pitch: 1.0 }
    - { name: ITEM_GOAT_HORN_SOUND_4, volume: 10.0, pitch: 1.15 }
    - { name: ENTITY_VILLAGER_CELEBRATE, volume: 6.0, pitch: 1.0 }
    - { name: ENTITY_PLAYER_LEVELUP, volume: 6.0, pitch: 1.0 }
    - { name: UI_TOAST_CHALLENGE_COMPLETE, volume: 6.0, pitch: 1.0 }
    - { name: BLOCK_BEACON_ACTIVATE, volume: 6.0, pitch: 1.0 }
    - { name: ENTITY_FIREWORK_ROCKET_LAUNCH, volume: 6.0, pitch: 1.0 }

particles:
  enabled: true
  type: FIREWORKS_SPARK
  count: 250
  extra: 0.1
  offset: { x: 1.5, y: 1.5, z: 1.5 }

confetti:
  enabled: true
  bursts: 3               # number of quick bursts
  per_burst: 200          # particles per burst
  colors: ["#FF006E", "#FFBE0B", "#3A86FF", "#8AC926", "#FF595E"]

fireworks:
  enabled: true
  per_player: 4
  power: 2
  colors: ["#FFD700", "#FF4500", "#00FFFF"]
  fade_colors: ["#FFFFFF"]
  flicker: true
  trail: true

effects:
  enabled: true
  list:
    - { name: GLOWING, duration_ticks: 100, amplifier: 0 }
    - { name: SPEED, duration_ticks: 160, amplifier: 1 }
    - { name: JUMP, duration_ticks: 100, amplifier: 1 }

lightning:
  enabled: true
  bolts_per_player: 2
  radius: 3.0             # random radius around each player (visual only)

hologram:
  enabled: true
  text: "&6All hail &e%player%&6!"
  seconds: 4

messages:
  chat_broadcast: "&6⚔ &e%player% &6(&eOP&6) has joined. All hail!"
