name: GrandEntrance
version: 1.1.1
main: com.itharia.grandentrance.GrandEntrancePlugin
api-version: '1.21'
author: MoneyMantra
description: Operator join goes nuclear: trumpets, fireworks, particles, confetti, lightning, bossbar, hologram, effects.
commands:
  grandentrance:
    description: GrandEntrance admin commands
    usage: /<command> reload
    aliases: [ge, gea]
    permission: grandentrance.admin
permissions:
  grandentrance.admin:
    default: op
  grandentrance.trigger:
    default: op
  grandentrance.silent:
    default: false
